# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 658dfffe52578679fa71627c4bb882d93f80575603bcb4ecc7dc425022ce7796f26fe52585a212d6ec34ef5b917c346d4fefe7bfc81df01a71485e0adef68322

test:
  secret_key_base: a5975b7de463bfba32ba3c32fdf3ecd0509ce009f9a0e7603ba49c34c7294785e05f7da415805362022faf8d860d306b0d8d02b17114e873a7fb1d917de774ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
